name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        nim:
          - '2.2.4'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    name: Build nim circom compat ${{ matrix.nim }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set rust ${{ matrix.os }}
        if: matrix.os == 'windows-latest'
        run: |
          rustup set default-host x86_64-pc-windows-gnu
          rustup update stable
          rustup default 1.85.0

      - name: Set rust ${{ matrix.os }}
        if: matrix.os != 'windows-latest'
        run: rustup update stable && rustup default 1.85.0

      - name: Setup nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble install -y
      - run: nimble test -y
